//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoEmpresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpleadoEmpresa()
        {
            this.Asistencia = new HashSet<Asistencia>();
            this.ClaveTemporal = new HashSet<ClaveTemporal>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int idEmpleado { get; set; }
        public System.DateTime fechaIng { get; set; }
        public int tipoPuesto { get; set; }
        public int tipoContrato { get; set; }
        public System.TimeSpan horaEntrada { get; set; }
        public System.TimeSpan horaSalida { get; set; }
        public decimal salario { get; set; }
        public byte[] huella { get; set; }
        public bool estatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asistencia> Asistencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaveTemporal> ClaveTemporal { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual EmpleadoPersonal EmpleadoPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        public virtual Puesto Puesto { get; set; }
    }
}
