//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpleadoPersonal
    {
        public int idEmpleado { get; set; }
        public string nombre { get; set; }
        public string apellidoM { get; set; }
        public string apellidoP { get; set; }
        public System.DateTime fechaNac { get; set; }
        public string telefono { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
    
        public virtual EmpleadoEmpresa EmpleadoEmpresa { get; set; }
    }
}
