//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public System.DateTime dia { get; set; }
        public int idEmpleado { get; set; }
        public System.TimeSpan horaEntrada { get; set; }
        public Nullable<System.TimeSpan> horaSalida { get; set; }
    
        public virtual EmpleadoEmpresa EmpleadoEmpresa { get; set; }
    }
}
