//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AsistenciaEntities : DbContext
    {
        public AsistenciaEntities()
            : base("name=AsistenciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asistencia> Asistencia { get; set; }
        public virtual DbSet<ClaveTemporal> ClaveTemporal { get; set; }
        public virtual DbSet<Contrato> Contrato { get; set; }
        public virtual DbSet<EmpleadoEmpresa> EmpleadoEmpresa { get; set; }
        public virtual DbSet<EmpleadoPersonal> EmpleadoPersonal { get; set; }
        public virtual DbSet<Puesto> Puesto { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
